name: Eel Build and Publish

on:
    push:
        tags:
            - 'v*'

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Cache Node.js packages
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/web/package-lock.json') }}

            - name: Install Node.js dependencies
              run: |
                  cd web
                  npm install

            - name: Build Web
              run: |
                  cd web
                  npm run build

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'

            - name: Cache Python packages
              uses: actions/cache@v2
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install Python dependencies
              run: |
                  pip install -r requirements.txt
                  pip install pyinstaller

            - name: Build executable
              run: |
                  python -m eel main.py web/dist --add-data "images;images" --add-data "config.ini;." --noconfirm --noconsole --name mhxy_script

            - name: Upload Build Files
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: ./dist

    publish:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download Build Files
              uses: actions/download-artifact@v2
              with:
                  name: dist

            - name: Zip Build
              run: |
                  zip -r mhxy_script.zip mhxy_script

            - name: Create Release
              uses: actions/create-release@v1.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      Release ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1.0.1
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./mhxy_script.zip
                  asset_name: mhxy_script.zip
                  asset_content_type: application/zip
